apiVersion: v1
kind: Service
metadata:
  name: price-pred-ml-kube-train-service
spec:
  selector:
    app: price-pred-ml-kube-train
  type: NodePort  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 32000
  